### ISSUE TITLE
Add more image quality metrics

### ISSUE THREAD

**Issue by iarganda** [BiaPyX/BiaPy#46]
So far, only PSNR is implemented.
Possible metrics to include are:
- SSIM
- MAE
- MSE
- Perceptual metrics
- ... 

@IvanHCenalmor

**Comment by danifranco** [comment]
Done in [f872e1f](https://github.com/BiaPyX/BiaPy/commit/f872e1fd74fe55b66c694ef0289bb07495265c5f)
