### ISSUE TITLE
Link to templates from Docs broken for Super-resolution

### ISSUE THREAD

**Issue by Mohinta2892** [BiaPyX/BiaPy#69]
Hi Dani,

Could you please fix the links to the templates files from the documentation?

Path to template: https://github.com/BiaPyX/BiaPy/blob/master/templates/super_resolution/2d_super-resolution.yaml

![image](https://github.com/BiaPyX/BiaPy/assets/44754434/0c3730c0-2ae3-4e01-b8c2-d0b758e3c159)
****

Thanks,
Samia

**Comment by danifranco** [comment]
Thank you so much for pointing out the error Samia. I've just corrected it so I'm closing the issue.
