### ISSUE TITLE
Incorrect number of epochs on metric plot

### ISSUE THREAD

**Issue by iarganda** [BiaPyX/BiaPy#72]
The number of epochs in the metric chart appears to be larger than that of the loss chart when using several metrics. See for instance:
![snemi3d_resunet_A_2_jaccard_index](https://github.com/BiaPyX/BiaPy/assets/4041131/3a1597d4-c52f-4e60-9b48-55da6a9aed22)
![snemi3d_resunet_A_2_loss](https://github.com/BiaPyX/BiaPy/assets/4041131/1182697e-72ab-4813-8c75-5dd901447593)
My guess is it is related to the number of metrics. In this example, I used the Jaccard index three times, one per channel.

**Comment by danifranco** [comment]
Fixed in last commit: [e429462d](https://github.com/BiaPyX/BiaPy/commit/e429462dfdf318feb2a348e2d542d9112b270e18)
