### ISSUE TITLE
Add more options to select patches for training

### ISSUE THREAD

**Issue by danifranco** [BiaPyX/BiaPy#75]
The idea is to have more options apart from ``DATA.TRAIN.MINIMUM_FOREGROUND_PER``. Intensity based measurements seem to be useful for users, e.g. mean, min/max, std (see [forum.sc thread](https://forum.image.sc/t/neuron-cell-detection-biapy/94198/10)).

**Comment by pr4deepr** [comment]
Just to add, this would be very useful for inference as well..

**Comment by danifranco** [comment]
Hello @pr4deepr !

We have implemented the filtering for training/validation and test (ad6329716457f7d860eb8dc4964109b6f9e7e394). You can use it with `DATA.*.FILTER_SAMPLES` variables (e.g. [train variables here](https://github.com/BiaPyX/BiaPy/blob/91afc78d4384cf276059f579a93fdfaecf5a1e80/biapy/config/config.py#L288)). Hope you like it!

I'm closing this but feel free to create a new issue if you have any problem.
