### ISSUE TITLE
bug: import error: pytorch_msssim 

### ISSUE THREAD

**Issue by pr4deepr** [BiaPyX/BiaPy#77]
I was testing the master repo and I got this error when I started training:

```
from pytorch_msssim import ssim, ms_ssim, SSIM, MS_SSIM
ModuleNotFoundError: No module named 'pytorch_msssim
```

Cheers
Pradeep

**Comment by danifranco** [comment]
I'm updating the dependencies now, [pytorch_msssim](https://pypi.org/project/pytorch-msssim/) needs to be installed in your environment.
