### ISSUE TITLE
documentation suggestion

### ISSUE THREAD

**Issue by pr4deepr** [BiaPyX/BiaPy#78]
You mentioned we could normalized by image or dataset, but I couldn't find the documentation for what value I should give [DATA.NORMALIZATION.APPLICATION_MODE](https://github.com/BiaPyX/BiaPy/blob/e923efcb8b2497d5f8e36f2402d7be7794bf01d5/biapy/config/config.py#L188) if I wanted to normalize by entire dataset stats. I found it in the[ code](https://github.com/BiaPyX/BiaPy/blob/e429462dfdf318feb2a348e2d542d9112b270e18/biapy/engine/check_configuration.py#L515) that I should use the value 'dataset'. It would be worth including that in the documentation.

Unless I completely missed it!!

**Comment by danifranco** [comment]
Yeah, that's true. I'll add a proper description there and change the [normalization section in our doc](https://biapy.readthedocs.io/en/latest/get_started/configuration.html#data-normalization) aswell.
